# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: convosphere_backend/grpc/convosphere_backend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2convosphere_backend/grpc/convosphere_backend.proto\x12\'convosphere_backend.convosphere_backend\"\xaf\x01\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x06parent\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\r\n\x05topic\x18\x03 \x01(\x03\x12\x0e\n\x06sender\x18\x04 \x01(\x05\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x11\n\tsent_time\x18\x06 \x01(\t\x12\x16\n\tedit_time\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x12\n\nis_deleted\x18\x08 \x01(\x08\x42\t\n\x07_parentB\x0c\n\n_edit_time\"P\n\x0bMessageList\x12\x41\n\x07results\x18\x01 \x03(\x0b\x32\x30.convosphere_backend.convosphere_backend.Message\"\x14\n\x12MessageListRequest\"\xe3\x01\n\x1bMessagePartialUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x06parent\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\r\n\x05topic\x18\x03 \x01(\x03\x12\x0e\n\x06sender\x18\x04 \x01(\x05\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x12\n\nis_deleted\x18\x07 \x01(\x08\x12\x1e\n\x16_partial_update_fields\x18\x08 \x03(\t\x12\x16\n\tedit_time\x18\t \x01(\tH\x01\x88\x01\x01\x12\x11\n\tsent_time\x18\n \x01(\tB\t\n\x07_parentB\x0c\n\n_edit_time\"$\n\x16MessageRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xfd\x04\n\x11MessageController\x12n\n\x06\x43reate\x12\x30.convosphere_backend.convosphere_backend.Message\x1a\x30.convosphere_backend.convosphere_backend.Message\"\x00\x12{\n\x04List\x12;.convosphere_backend.convosphere_backend.MessageListRequest\x1a\x34.convosphere_backend.convosphere_backend.MessageList\"\x00\x12\x89\x01\n\rPartialUpdate\x12\x44.convosphere_backend.convosphere_backend.MessagePartialUpdateRequest\x1a\x30.convosphere_backend.convosphere_backend.Message\"\x00\x12\x7f\n\x08Retrieve\x12?.convosphere_backend.convosphere_backend.MessageRetrieveRequest\x1a\x30.convosphere_backend.convosphere_backend.Message\"\x00\x12n\n\x06Update\x12\x30.convosphere_backend.convosphere_backend.Message\x1a\x30.convosphere_backend.convosphere_backend.Message\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convosphere_backend.grpc.convosphere_backend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=96
  _MESSAGE._serialized_end=271
  _MESSAGELIST._serialized_start=273
  _MESSAGELIST._serialized_end=353
  _MESSAGELISTREQUEST._serialized_start=355
  _MESSAGELISTREQUEST._serialized_end=375
  _MESSAGEPARTIALUPDATEREQUEST._serialized_start=378
  _MESSAGEPARTIALUPDATEREQUEST._serialized_end=605
  _MESSAGERETRIEVEREQUEST._serialized_start=607
  _MESSAGERETRIEVEREQUEST._serialized_end=643
  _MESSAGECONTROLLER._serialized_start=646
  _MESSAGECONTROLLER._serialized_end=1283
# @@protoc_insertion_point(module_scope)
