# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from convosphere_backend.grpc import convosphere_backend_pb2 as convosphere__backend_dot_grpc_dot_convosphere__backend__pb2


class MessageControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/convosphere_backend.convosphere_backend.MessageController/Create',
                request_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
                response_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
                )
        self.List = channel.unary_unary(
                '/convosphere_backend.convosphere_backend.MessageController/List',
                request_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageListRequest.SerializeToString,
                response_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageList.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/convosphere_backend.convosphere_backend.MessageController/PartialUpdate',
                request_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessagePartialUpdateRequest.SerializeToString,
                response_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/convosphere_backend.convosphere_backend.MessageController/Retrieve',
                request_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageRetrieveRequest.SerializeToString,
                response_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
                )
        self.Update = channel.unary_unary(
                '/convosphere_backend.convosphere_backend.MessageController/Update',
                request_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
                response_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
                )


class MessageControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
                    response_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageListRequest.FromString,
                    response_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageList.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessagePartialUpdateRequest.FromString,
                    response_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageRetrieveRequest.FromString,
                    response_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
                    response_serializer=convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'convosphere_backend.convosphere_backend.MessageController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/convosphere_backend.convosphere_backend.MessageController/Create',
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/convosphere_backend.convosphere_backend.MessageController/List',
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageListRequest.SerializeToString,
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/convosphere_backend.convosphere_backend.MessageController/PartialUpdate',
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessagePartialUpdateRequest.SerializeToString,
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/convosphere_backend.convosphere_backend.MessageController/Retrieve',
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.MessageRetrieveRequest.SerializeToString,
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/convosphere_backend.convosphere_backend.MessageController/Update',
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.SerializeToString,
            convosphere__backend_dot_grpc_dot_convosphere__backend__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
